---

# Packages

- name: Install packages from the official repo
  apt:
    name:
      - htop
      - vim
      - cryptsetup
      - bzip2
      - fish
      - whois
    state: present
    update_cache: yes
  environment:
    RUNLEVEL: 1
    

# Users and groups

- name: Create shared group
  group:
      name: "{{ general.shared_group }}"
      state: present

- name: Create or update users
  user:
      name: "{{ item.name }}"
      home: "/mnt/{{ drives[general.homes_drive].name }}/homes/{{ item.name }}"
      create_home: yes
      groups:
        - "{{ general.shared_group }}"
      state: present # not required. choices: absent;present. Whether the account should exist or not, taking action if the state is different from what is stated.
  with_items: "{{ users }}"

